import { useEffect, useState } from "react";
import {
  Alert,
  Button,
  FormControlLabel,
  Paper,
  Stack,
  Switch,
  TextField,
  Typography
} from "@mui/material";
import { ensureEndpointAccess } from "../settings/browser-access";
import {
  bridgePermissionUrl,
  BRIDGE_STATUS_KEY,
  DEFAULT_BRIDGE_SETTINGS,
  loadBridgeSettings,
  loadBridgeStatus,
  saveBridgeSettings,
  type BridgeSettings,
  type BridgeStatus
} from "../settings/bridge-store";

export function BridgeSettingsSection() {
  const [settings, setSettings] =
    useState<BridgeSettings>(DEFAULT_BRIDGE_SETTINGS);
  const [status, setStatus] = useState<BridgeStatus>({
    state: "disabled",
    changed_at: new Date().toISOString()
  });
  const [message, setMessage] = useState("");

  useEffect(() => {
    void loadBridgeSettings().then(setSettings);
    void loadBridgeStatus().then(setStatus);

    const onStorage = (
      changes: Record<string, chrome.storage.StorageChange>,
      areaName: string
    ) => {
      if (
        areaName === "session" &&
        changes[BRIDGE_STATUS_KEY]?.newValue
      ) {
        setStatus(changes[BRIDGE_STATUS_KEY].newValue);
      }
    };

    chrome.storage.onChanged.addListener(onStorage);
    return () => chrome.storage.onChanged.removeListener(onStorage);
  }, []);

  const save = async () => {
    try {
      if (settings.enabled) {
        const granted = await ensureEndpointAccess(
          bridgePermissionUrl(settings.address)
        );
        if (!granted) {
          setMessage(
            "Chrome did not grant access to the local bridge address."
          );
          return;
        }
      }

      await saveBridgeSettings(settings);
      setMessage(
        settings.enabled
          ? "Bridge settings saved. BrowserCrew will connect to the local daemon."
          : "Local Agent Bridge disabled."
      );
    } catch (error) {
      setMessage(
        error instanceof Error
          ? error.message
          : "Could not save bridge settings."
      );
    }
  };

  const severity =
    status.state === "connected"
      ? "success"
      : status.state === "error"
        ? "error"
        : "info";

  return (
    <Paper variant="outlined" sx={{ p: 2 }}>
      <Stack spacing={1.5}>
        <Typography variant="subtitle1">
          Local Agent Bridge
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Let local tools such as Hermes, Codex, Claude Code or another
          agent control BrowserCrew through the loopback-only bridge.
          BrowserCrew task sessions, semantic refs and approval policy still apply.
        </Typography>

        <FormControlLabel
          control={
            <Switch
              checked={settings.enabled}
              onChange={(event) =>
                setSettings((current) => ({
                  ...current,
                  enabled: event.target.checked
                }))
              }
            />
          }
          label="Enable local agent remote control"
        />

        <TextField
          label="Bridge address"
          value={settings.address}
          onChange={(event) =>
            setSettings((current) => ({
              ...current,
              address: event.target.value
            }))
          }
          placeholder="ws://127.0.0.1:10087/ws"
          fullWidth
        />

        <TextField
          label="Pairing token"
          value={settings.token}
          onChange={(event) =>
            setSettings((current) => ({
              ...current,
              token: event.target.value
            }))
          }
          type="password"
          autoComplete="off"
          fullWidth
          helperText="Generated by the local BrowserCrew Bridge daemon. Stored only in extension-local storage."
        />

        <Alert severity={severity}>
          Bridge: {status.state}
          {status.message ? ` · ${status.message}` : ""}
        </Alert>

        {message && <Alert severity="info">{message}</Alert>}

        <Button variant="outlined" onClick={() => void save()}>
          Save bridge settings
        </Button>
      </Stack>
    </Paper>
  );
}
